#
# simple example to run extconf.rb
#
#
# with PostgreSQL >= 7.2, if the headers files are installed
#   (make install-all-headers)
# you just need to specify pgsql-prefix
#
ruby extconf.rb --with-pgsql-dir=/home/ts/local/pgsql
#
# for developpement version (version is not defined)
# with the new style of function call
#
# ruby extconf.rb --with-pgsql-dir=/home/ts/local/pgtemp \
#   --with-pgsql-srcinc=/home/ts/postgresql/pgsql/src/include \
#   --with-pgsql-version=71
#
