#
# simple example to run extconf.rb
#
ruby extconf.rb --with-pgsql-prefix=/home/ts/local/pgsql \
  --with-pgsql-srcinc-dir=/home/ts/postgresql/postgresql-7.0.1/src/include
#
# for developpement version (version is not defined)
# with the new style of function call
#
# ruby extconf.rb --with-pgsql-prefix=/home/ts/local/pgtemp \
#   --with-pgsql-srcinc-dir=/home/ts/postgresql/pgsql/src/include \
#   --with-pgsql-version=7
#
