#!/bin/sh

DBNAME=plruby_test
export DBNAME

sleep 1
echo "**** Destroy old database $DBNAME ****"
dropdb $DBNAME

echo "**** Create test database $DBNAME ****"
createdb $DBNAME

echo "**** Create procedural language plruby$2 ****"
"${RUBY-ruby}" b.rb $*
psql -q -n -X $DBNAME < test_mklang.sql

echo "**** Create tables, functions and triggers ****"
psql -q -n -X $DBNAME < test_setup.sql

echo "**** Running test queries ****"
psql -q -n -X -e $DBNAME < test_queries.sql > test.out 2>&1

if cmp -s test.expected.$1 test.out; then
    echo "    Tests passed O.K."
else
    echo "    Tests failed - look at diffs between"
    echo "    test.expected.$1 and test.out"
fi

